spring.application.name=filmreviewer

# JDBC URL (Observă formatul: jdbc:postgresql://HOST:PORT/DATABASE)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres

# Username-ul extras
spring.datasource.username=postgres.yeozvyzegkqzqtielgmv

# Parola ta reală de la Supabase
spring.datasource.password=MciOzV7zjS1PTRLz

# Driver-ul pentru PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Foarte important pentru Supabase (previne închiderea conexiunii)
spring.datasource.hikari.keepaliveTime=30000

# Această linie îi spune lui Hibernate să creeze tabelul dacă nu există, sau să îl actualizeze
spring.jpa.hibernate.ddl-auto=update
